Adds Login screen
feedhenry/snapscreen pull request #1
Opened 2017-04-13 15:00 UTC by damienomurchu

wip on login screen functionality - not ready to be merged yet

@pmdarrow @emilioicai might get your thoughts/ eyes as pretty new to react-native

2017-04-13 15:45 UTC, emilioicai commented on client/app/screens/LoginScreen.js
> +  welcome: {
this seems not to be used?

2017-04-13 15:45 UTC, emilioicai commented on client/app/screens/LoginScreen.js
> +  instructions: {
this seems not to be used?

2017-04-13 15:45 UTC, emilioicai commented on client/app/components/Button.js
> +import React, { Component } from 'react';
I think @pmdarrow was using some kind of UI library. Maybe we can find a button and a Container components there so we don't need to create our owns

2017-04-13 16:03 UTC, damienomurchu commented on client/app/screens/LoginScreen.js
> +  welcome: {
+1 consider it gone

2017-04-13 16:03 UTC, damienomurchu commented on client/app/screens/LoginScreen.js
> +  instructions: {
+1 consider it gone

2017-04-13 16:04 UTC, damienomurchu commented on client/app/components/Button.js
> +import React, { Component } from 'react';
Yeah, will refactor this login screen with native-base components I think - just needed to get my hands dirty with writing some RN code a little first :D

2017-04-13 16:06 UTC, emilioicai approved these changes

2017-04-13 16:55 UTC, pmdarrow commented
@damienomurchu I recently added support for [prettier](https://github.com/prettier/prettier) so we don't have to nit pick over code style, so I'd recommend running it on your code here. You can do it with `yarn format`, and then commit the changes.

2017-04-13 17:10 UTC, pmdarrow requested changes

2017-04-13 17:10 UTC, pmdarrow commented on client/app/components/Button.js
> +import React, { Component } from 'react';
Good idea, you'll learn more playing around like this. When you're ready, check out https://docs.nativebase.io/COMPONENTS.html#Button_Default.

2017-04-13 17:10 UTC, pmdarrow commented on client/app/components/Button.js
> +const Button = (props) => {
If we were actually doing this, I'd make it a proper component, e.g. `class Button extends React.Component` instead of just an anonymous function.

2017-04-13 17:10 UTC, pmdarrow commented on client/app/components/Container.js
> +const Container = (props) => {
Same as above - not necessary with native-base but if I were doing it, I'd make it a proper react component (e.g. `class Container extends React.Component`)

2017-04-13 17:10 UTC, pmdarrow commented on client/app/components/Label.js
> +const Label = (props) => {
https://docs.nativebase.io/COMPONENTS.html#Form when you're ready 😄

2017-04-13 17:10 UTC, pmdarrow commented on client/app/screens/LoginScreen.js
> +import Icon from 'react-native-vector-icons/FontAwesome';
Icons are actually included in native-base as well, https://docs.nativebase.io/COMPONENTS.html#Icon_Default. Sorry if I sound like a broken record 😆

2017-04-18 09:31 UTC, damienomurchu commented on client/app/screens/LoginScreen.js
> +import Icon from 'react-native-vector-icons/FontAwesome';
Not at all - beginnging to dig into native-base now :)

2017-04-19 16:34 UTC, damienomurchu commented
Refactored the login screen to lean on native-base pre-built components

2017-04-20 09:13 UTC, damienomurchu commented
Adds signup screen & rebased code so commit refs changed - only new code from commit cb71192 onwards

2017-04-26 13:55 UTC, secondsun commented
I've integrated a lot of this PR into https://github.com/feedhenry/snapscreen/pull/5 closing.

2017-04-26 13:55 UTC, closed without merging