Add that it was a demo for the summit
feedhenry/snapscreen pull request #21
Opened 2018-06-13 15:15 UTC by camilamacedo86

demo app for the summit

2018-06-13 16:09 UTC, damienomurchu commented on README.md
> +SnapScreen is a project which demonstrates how to use Keycloak, AeroGear Unified Push Server, and OpenShift with React Native. It was created as a demo app for the RedHat summit (2017).
I would just change `RedHat summit (2017)` to `Red Hat Summit 2017` to match with how we officially refer to Summit like [here](https://www.redhat.com/en/summit/2018)

2018-06-13 16:10 UTC, damienomurchu requested changes
Comment left re changing the wording slightly. Happy to approve once changed

2018-06-13 17:04 UTC, camilamacedo86 commented
@damienomurchu done 👍

2018-06-14 07:31 UTC, austincunningham approved these changes

2018-06-14 08:26 UTC, damienomurchu approved these changes

2018-06-14 08:32 UTC, merged